pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "hello-world-angular"
        DOCKER_TAG = "latest"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/ArchiChaudhari/angular-web-app.git'
            }
        }

        stage('Setup Node.js Environment') {
            steps {
                script {
                    // Check if Node.js is installed; install if missing
                    if (sh(returnStatus: true, script: 'command -v node') != 0) {
                        echo "Node.js is not installed. Installing Node.js..."
                        sh '''
                            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
                            apt-get install -y nodejs
                        '''
                    } else {
                        echo "Node.js is already installed."
                    }
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build Angular App') {
            steps {
                sh 'npm run build --prod'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
            }
        }

        stage('Run Docker Container') {
            steps {
                sh "docker run -d -p 8080:80 --name ${DOCKER_IMAGE} ${DOCKER_IMAGE}:${DOCKER_TAG}"
            }
        }
    }

    post {
        always {
            sh "docker ps"
        }
    }
}
